while True:
     
    print()

    def pickanumber():
        print()
        print("In this game, you will guess a number between 1-5. A random number will be generated by the computer. If you're number is the same as the generated number, you win!")
        import random
        print()

        number=random.randint(1,5)
        choice=int(input("Enter your chosen number (between 1-5): "))
        print()

        print("CHOSEN NUMBER: "+str(choice))
        print("GENERATED NUMBER: "+str(number))
        print()

        if choice == number:
            print("You win! ")
        else:
            print("You lose :(")
        print()

    def rockpaperscissors():
        print()
        print("In this game, you will choose rock, paper or scissors. The computer will then choose rock, paper or scissors. Rock beats scissors, paper beats rock, scissors beat paper.")
        import random
        print()
        sign="hello"

        number=random.randint(1,3)
        choice=input("Enter your chosen sign (rock, paper or scissor): ")
        if number==1:
            sign="rock"
        elif number==2:
            sign="paper"
        else:
            sign="scissors"
        print()

        print("YOUR CHOSEN SIGN: "+str(choice.lower()))
        print("GENERATED SIGN: "+str(sign))
        print()

        if choice.lower() == "rock" and sign=="paper":
            print("The computer wins! ")
        elif choice.lower() == "paper" and sign=="scissors":
            print("The computer wins! ")
        elif choice.lower() == "scissors" and sign=="rock":
            print("The computer wins!")
        elif choice.lower() == "rock" and sign=="scissors":
            print("You win!")
        elif choice.lower() == "paper" and sign=="rock":
            print("You win!")
        elif choice.lower() == "scissors" and sign=="paper":
            print("You win!")
        else:
            print("Its a tie!")
        print()

    print("GAMES:")
    print("1 - Guess The Number")
    print("2 - Rock Paper Scissors")
    choice=input("Choose which game you want to play! ")
    if choice=="1":
        pickanumber()
    elif choice=="2":
        rockpaperscissors()
    again=input("Do you want to play again? ")
    if again.lower()=="yes":
        pass
    else:
        break