score=0
while True:
     
    print()

    def pickanumber():
        print()
        print("In this game, you will guess a number between 1-5. A random number will be generated by the computer. If you're number is the same as the generated number, you win!")
        import random
        print()

        number=random.randint(1,5)
        choice=int(input("Enter your chosen number (between 1-5): "))
        print()

        print("CHOSEN NUMBER: "+str(choice))
        print("GENERATED NUMBER: "+str(number))
        print()

        if choice == number:
            print("You win! ")
            return 1
        else:
            print("You lose :(")
        print()

    def rockpaperscissors():
        print()
        print("In this game, you will choose rock, paper or scissors. The computer will then choose rock, paper or scissors. Rock beats scissors, paper beats rock, scissors beat paper.")
        import random
        print()
        sign="hello"

        number=random.randint(1,3)
        choice=input("Enter your chosen sign (rock, paper or scissors): ")
        if number==1:
            sign="rock"
        elif number==2:
            sign="paper"
        else:
            sign="scissors"
        print()

        print("YOUR CHOSEN SIGN: "+str(choice.lower()))
        print("GENERATED SIGN: "+str(sign))
        print()

        if choice.lower() == "rock" and sign=="paper":
            print("The computer wins! ")
        elif choice.lower() == "paper" and sign=="scissors":
            print("The computer wins! ")
        elif choice.lower() == "scissors" and sign=="rock":
            print("The computer wins!")
        elif choice.lower() == "rock" and sign=="scissors":
            print("You win!")
            return 1
        elif choice.lower() == "paper" and sign=="rock":
            print("You win!")
            return 1
        elif choice.lower() == "scissors" and sign=="paper":
            print("You win!")
            return 1
        else:
            print("Its a tie!")
        print()
    
    def flipacoin():
        print()
        print("In this game, you will guess whether the coin lands on heads or tails. If you are right, you win! ")
        import random
        number=random.randint(1,2)
        if number==1:
            coin="Heads"
        else:
            coin="Tails"
        choice=input("Enter your guess: ")
        if choice.lower()=="heads" and number==1:
            print("You win!")
            return 1
        elif choice.lower()=="tails" and number == 2:
            print("You win!")
            return 1
        else:
            print("You lose")

    def wordle():
        import random
        print()
        print("In this game, you will have six guesses to guess a five-letter word. If a letter is correct, but in the wrong place, it is underlined. If it is correct in the right place, it will become bold. Your list of unguessed letters will appear at the start of each guess to help you make your guess. Careful though, you only get six :)")
        alpha=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
        wordindex=random.randint(1,10)
        if wordindex==1:
            word="artsy"
        elif wordindex==2:
            word="spout"
        elif wordindex==3:
            word="choir"
        elif wordindex==4:
            word="lover"
        elif wordindex==5:
            word="dirty"
        elif wordindex==6:
            word="slept"
        elif wordindex==7:
            word="sound"
        elif wordindex==8:
            word="wordy"
        elif wordindex==9:
            word="poems"
        else:
            word="wider"
        wordfound=0
        count=0

        def checkifthere():
            for letter in alpha:
                if letter == newalpha:
                    return True
            return False  # Only return False after checking all elements


        while wordfound==0:
            print("Unguessed letters: ")
            print(alpha)
            a=input("Enter your guess: ")
            count=count+1
            boulder=""
            add=0
            for i in range(5): 
                if a[i] == word[i]:
                    newalpha="\033[1m"+ a[i] +"\033[0m"
                    boulder=boulder+newalpha
                    add=add+1
                    if checkifthere() == True:
                        alpha.remove(a[i])
                else:
                    for m in range(1,5):
                        check=0
                        underline=False
                        if a[i]==word[m]:
                            underline=True
                            check=1
                        if underline==True:
                            newalpha="\033[4m"+ a[i] +"\033[0m"
                            boulder=boulder+newalpha
                            if checkifthere() == True:
                                alpha.remove(a[i])
                            break
                    if check==0:
                        boulder=boulder+a[i]
                        newalpha=a[i]
                        if checkifthere() == True:
                            alpha.remove(a[i])
            if add==5:
                print("You win!")
                return 1
            elif count==6:
                print("Sorry, you ran out of guesses, you lose!")
                return 0
            print(boulder)

    increase=0
    print("LUCK GAMES:")
    print("1 - Guess The Number")
    print("2 - Rock Paper Scissors")
    print("3 - Flip a Coin")
    print("4 - Wordle")
    choice=input("Choose which game you want to play! ")
    if choice=="1":
        increase=pickanumber()
    elif choice=="2":
        increase=rockpaperscissors()
    elif choice=="3":
        increase=flipacoin()
    elif choice=="4":
        increase=wordle()
    
    if increase==1:
            score=score+1
    print("Your current score is "+str(score)+".")
    again=input("Do you want to play again? ")
    if again.lower()=="yes":
        pass
    else:
        break
